apiVersion: v1
appVersion: 0.111.4
description: Home Assistant
name: home-assistant
version: 1.0.1
keywords:
- home-assistant
- hass
- homeassistant
home: https://github.com/RuneRoven/charts
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
sources:
- https://github.com/home-assistant/home-assistant
- https://github.com/danielperna84/hass-configurator
- https://github.com/cdr/code-server
maintainers:
- name: Daniel
  email: none@none.com
